package com.test.mongotest.model;

import lombok.Builder;

import java.util.Arrays;
import java.util.List;

@Builder
public class WordList {
    public static List<String> Words;
    static {
        Words = Arrays.asList(
                "Levy",
                "Duty",
                "Tariff",
                "Excise",
                "Customs",
                "Import",
                "Export",
                "Value-added",
                "Sales",
                "Use",
                "Property",
                "Inheritance",
                "Gift",
                "Payroll",
                "Income",
                "Capital gains",
                "Corporate",
                "Self-employment",
                "Social security",
                "Medicare",
                "Excise",
                "Franchise",
                "Excise",
                "Ad valorem",
                "Sales tax",
                "Business tax",
                "Excise tax",
                "Consumption tax",
                "Luxury tax",
                "Sin tax",
                "Flat tax",
                "Progressive tax",
                "Regressive tax",
                "Tax rate",
                "Tax bracket",
                "Tax base",
                "Tax credit",
                "Tax deduction",
                "Tax exemption",
                "Tax shelter",
                "Tax evasion",
                "Tax fraud",
                "Tax haven",
                "Tax avoidance",
                "Tax relief",
                "Tax refund",
                "Tax lien",
                "Tax levy",
                "Tax notice",
                "Tax assessment",
                "Tax return",
                "Tax 5060deadline",
                "Tax forms",
                "Tax accountant",
                "Tax attorney",
                "Tax preparation",
                "Tax planning",
                "Tax audit",
                "Tax appeal",
                "Tax settlement",
                "Tax collection",
                "Tax law",
                "Tax code",
                "Tax policy",
                "Tax reform",
                "Tax system",
                "Taxation",
                "Fiscal policy",
                "Budget",
                "Deficit",
                "Debt",
                "Revenue",
                "Expenditure",
                "Surplus",
                "Burden",
                "Fairness",
                "Equity",
                "Justice",
                "Document",
                "Spreadsheet",
                "Presentation",
                "Text",
                "Image",
                "Audio",
                "Video",
                "Archive",
                "Database",
                "PDF",
                "CSV",
                "Excel",
                "Word",
                "PowerPoint",
                "HTML",
                "ZIP",
                "RAR",
                "Executable",
                "Script",
                "Configuration",
                "Log",
                "Backup",
                "Encrypted",
                "Compressed",
                "Shared",
                "Collaborative",
                "Protected",
                "Private",
                "Public",
                "Read-only",
                "Editable",
                "Writeable",
                "Viewable",
                "Printable",
                "Downloadable",
                "Uploadable",
                "Syncable",
                "Versioned",
                "Timestamped",
                "Tagged",
                "Indexed",
                "Searchable",
                "Sortable",
                "Filtered",
                "Formatted",
                "Annotated",
                "Commented",
                "Described",
                "Named",
                "Titled",
                "Labeled",
                "Filed",
                "Stored",
                "Retrieved",
                "Deleted",
                "Moved",
                "Copied",
                "Pasted",
                "Cut",
                "Undo",
                "Redo",
                "Save",
                "Save As",
                "Save Copy",
                "Save Version",
                "Save Backup",
                "Open",
                "Close",
                "Quit",
                "Exit",
                "Restart",
                "Shutdown",
                "Update",
                "Upgrade",
                "Install",
                "Uninstall",
                "Enable",
                "Disable",
                "Repair",
                "Fix",
                "Troubleshoot",
                "Optimize",
                "Clean",
                "Secure",
                "Protect",
                "Defend",
                "Scan",
                "Monitor",
                "Audit",
                "Analyze",
                "Inspect",
                "Validate",
                "Test",
                "Verify",
                "Certify",
                "Accredit",
                "Authorize",
                "Approve",
                "Reject",
                "Deny",
                "Block",
                "Quarantine",
                "Isolate",
                "Recover",
                "Restore",
                "Resolve",
                "Confirm",
                "Dismiss",
                "Ignore",
                "Cancel",
                "Interrupt",
                "Pause",
                "Resume",
                "Abort",
                "Stop",
                "Wait",
                "Continue",
                "Start",
                "Begin",
                "End",
                "Complete",
                "Finish",
                "Submit",
                "Retry",
                "Revert",
                "Redirect",
                "Exit",
                "Return",
                "Clear",
                "Reset",
                "Refresh");
    }

}
