spring:
  application:
    name: 'mongo-test'

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  data:
    mongodb:
      uri: mongodb+srv://<username>:<password>@glb-dev.g6r6v.mongodb.net/glb-dev-test?tls=true&tlsInsecure=true
      database: glb-dev-test

swagger:
  version: v2
  description: 'Mongo Test'
  applicationName: ${spring.application.name:Springdoc OpenAPI}
  basePath: ${SWAGGER_BASE_PATH:/api/v2}

springdoc:
  local: ${SWAGGER_LOCAL:false}
  api-docs:
    enabled: ${SWAGGER_ENABLED:true}
  swagger-ui:
    docExpansion: none

